### ISSUE TITLE
Getting `Error: ENOENT: no such file or directory, lstat '/var/folders'` error from tempy's use of temp-dir

### ISSUE THREAD

**Issue by seunggs** [sindresorhus/tempy#40]
Hi, I have a create-react-app running in a Docker container and suddenly started seeing this error. Any tips as to why this might be occuring? Thanks!

```
node:fs:2486
      handleErrorFromBinding(ctx);
      ^

Error: ENOENT: no such file or directory, lstat '/var/folders'
    at Object.realpathSync (node:fs:2486:7)
    at Object.<anonymous> (/app/node_modules/temp-dir/index.js:9:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/tempy/index.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/var/folders'
}
```

**Comment by sindresorhus** [comment]
That sounds like a Node.js bug. You should report it there instead.

`os.tmpdir()` is expected to return a directory that exists:

https://github.com/sindresorhus/temp-dir/blob/9c5a61a05af0fdd74180b3bc5a5476e0886a9f46/index.js#L9
